/**
 * Mock menu items seeded from existing content.js FEATURED_ITEMS and SERVICES categories.
 * MOCK DATA - Replace with real API data when backend is ready.
 */

export const MOCK_MENU_ITEMS = [
  {
    id: 'menu-001',
    name: 'Mangonada Grande',
    description: 'Our signature frozen mango blend with chamoy swirl, fresh lime, and a chili-salt rim. Sweet, tangy, and refreshing.',
    price: 8.99,
    category: 'mangonadas',
    available: true,
    featured: true,
    photo: null,
    badge: 'Best Seller',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-20T14:30:00Z',
  },
  {
    id: 'menu-002',
    name: 'Fresas con Crema',
    description: 'Fresh strawberries layered with sweet cream, a drizzle of condensed milk, and a sprinkle of granola.',
    price: 7.49,
    category: 'cream-desserts',
    available: true,
    featured: true,
    photo: null,
    badge: 'Classic',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-18T11:00:00Z',
  },
  {
    id: 'menu-003',
    name: 'Elote Preparado',
    description: 'Grilled corn on the cob dressed with mayo, cotija cheese, chili powder, and a squeeze of lime.',
    price: 5.99,
    category: 'elotes-snacks',
    available: true,
    featured: true,
    photo: null,
    badge: 'Savory Pick',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
  },
  {
    id: 'menu-004',
    name: 'Bionico',
    description: 'A generous bowl of mixed fresh fruits topped with sweet cream, coconut, granola, and a honey drizzle.',
    price: 9.49,
    category: 'cream-desserts',
    available: true,
    featured: true,
    photo: null,
    badge: 'Fan Favorite',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-19T16:00:00Z',
  },
  {
    id: 'menu-005',
    name: 'Mangonada Pequena',
    description: 'A smaller version of our signature mangonada, perfect for a quick refreshing treat.',
    price: 5.99,
    category: 'mangonadas',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-03-10T12:00:00Z',
  },
  {
    id: 'menu-006',
    name: 'Chamoy Slushie',
    description: 'A frozen fruit slushie with chamoy drizzle, tamarind candy straw, and tajin rim.',
    price: 6.49,
    category: 'mangonadas',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-12T10:00:00Z',
  },
  {
    id: 'menu-007',
    name: 'Fresh Fruit Cup',
    description: 'Seasonal fresh fruit served in a cup with your choice of chamoy, tajin, or lime.',
    price: 6.99,
    category: 'fruit-cups',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'menu-008',
    name: 'Fruit Bowl Grande',
    description: 'A large bowl of seasonal fruits with all the toppings: chamoy, lime, tajin, and chili powder.',
    price: 9.99,
    category: 'fruit-cups',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-03-14T13:00:00Z',
  },
  {
    id: 'menu-009',
    name: 'Paleta de Mango',
    description: 'Handmade mango paleta dipped in chamoy and rolled in chili-lime seasoning.',
    price: 3.99,
    category: 'ice-cream',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'menu-010',
    name: 'Paleta de Fresa',
    description: 'Creamy strawberry paleta with real strawberry chunks. A classic favorite.',
    price: 3.99,
    category: 'ice-cream',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'menu-011',
    name: 'Esquites',
    description: 'Mexican-style corn in a cup with mayo, cotija cheese, lime, and chili powder.',
    price: 5.49,
    category: 'elotes-snacks',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-03-18T15:00:00Z',
  },
  {
    id: 'menu-012',
    name: 'Tostilocos',
    description: 'Crunchy tostitos topped with cucumber, jicama, chamoy, hot sauce, and lime.',
    price: 6.49,
    category: 'elotes-snacks',
    available: false,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'menu-013',
    name: 'Horchata',
    description: 'Traditional rice-based drink with cinnamon and vanilla. Served ice cold.',
    price: 3.99,
    category: 'aguas-frescas',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'menu-014',
    name: 'Agua de Jamaica',
    description: 'Refreshing hibiscus tea served cold with a touch of sweetness.',
    price: 3.49,
    category: 'aguas-frescas',
    available: true,
    featured: false,
    photo: null,
    badge: null,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'menu-015',
    name: 'Tres Leches Ice Cream',
    description: 'Rich tres leches flavored ice cream with a caramel swirl. Two scoops served in a waffle cone.',
    price: 5.49,
    category: 'ice-cream',
    available: true,
    featured: false,
    photo: null,
    badge: 'New',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
  },
];
